# Generated by Django 5.2.4 on 2025-08-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienthistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seller/'),
        ),
    ]
