# Generated by Django 5.2.4 on 2025-08-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_clienthistory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienthistory',
            name='image',
        ),
        migrations.AddField(
            model_name='seller',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seller/'),
        ),
    ]
