# Generated by Django 5.2.4 on 2025-08-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_clienthistory_image_seller_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
