# Generated by Django 5.2.4 on 2025-07-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caffe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='available',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
